name: Snyk Scan

runs:
  using: 'composite'

  steps:
    - name: Setup Snyk CLI
      uses: snyk/actions/setup@master

    - name: Run Snyk scan
      run: snyk test -d --all-projects --severity-threshold=high --sarif-file-output=snyk.sarif
      env:
        SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
      shell: bash

    - name: Snyk Code Scan.
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
      with:
        command: test
        args: --sarif-file-output=snyk-code.sarif --severity-threshold=high