name: Build and run tests

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
      with:
        distribution: 'corretto'
        java-version: '25'

    - name: Run build
      run: mvn -B clean package
      shell:
        bash

    - name: Find built JAR
      id: find-jar
      run: |
        JAR_FILE=$(ls target/*.jar)
        echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT
      shell: bash

    - name: Setup Snyk CLI
      uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04

    - name: Snyk scan JAR
      run: snyk test --file=$OUTPUT_FILE --sarif-file-output=snyk-jar.sarif --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
        OUTPUT_FILE: ${{ steps.find-jar.outputs.jar_file }}
      shell: bash

    - name: Upload SARIF to GitHub Security tab
      uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13
      with:
        sarif_file: snyk-jar.sarif