name: Feature build
on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  feature_branch:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Increment version
        run: |
          mvn versions:set -DnewVersion=1.2.5
          mvn versions:commit
          git add pom.xml
          git commit -m "chore: bump version to 1.2.4 [skip ci]"
          git push
