name: Increment openapi version number
on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  feature_branch:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up SSH signing key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OPENAPI_SIGNING_SSH }}" > ~/.ssh/signing_key
          chmod 600 ~/.ssh/signing_key  
          ssh-keygen -y -f ~/.ssh/signing_key > ~/.ssh/signing_key.pub
          chmod 644 ~/.ssh/signing_key.pub

      - name: Configure Git login for tags
          # Mandatory for version creation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ secrets.OPENAPI_SIGNING_SSH_USER }}"    
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/signing_key
          git config --global commit.gpgsign true

        shell: bash

      - name: Increment version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          mvn versions:set -DnewVersion=${NEW_VERSION}
          mvn versions:commit
          git add pom.xml
          git commit -S -m "chore: bump version to ${NEW_VERSION} [skip ci]"
          git push origin HEAD

      - name: Clean up SSH signing key
        if: always()
        run: |
          rm -f ~/.ssh/signing_key ~/.ssh/signing_key.pub