name: Increment openapi version number
on:
  workflow_dispatch:
  pull_request:
    types: [opened]

jobs:
  feature_branch:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Configure Git login for tags
          # Mandatory for version creation
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: Increment version
#         testing signed commits
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          mvn versions:set -DnewVersion=${NEW_VERSION}
          mvn versions:commit
          git add pom.xml
          git commit -S -m "chore: bump version to $NEW VERSION [skip ci]"
          git push origin HEAD